# Generated by Django 3.0.7 on 2020-07-13 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccionentrega',
            name='numeroInterior',
            field=models.IntegerField(default=None),
        ),
    ]
