# Generated by Django 3.0.7 on 2020-07-16 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200712_2324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipping_address',
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.ManyToManyField(blank=True, null=True, to='core.DireccionEntrega'),
        ),
    ]
