# Generated by Django 3.0.7 on 2020-07-17 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200716_1403'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='refund_granted',
            new_name='cancelled',
        ),
        migrations.RemoveField(
            model_name='order',
            name='refund_requested',
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.ManyToManyField(to='core.DireccionEntrega'),
        ),
    ]
