# Generated by Django 3.0.7 on 2020-07-25 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_order_ordered_date_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='image',
            field=models.ImageField(upload_to='media/core/images/'),
        ),
    ]
