# Generated by Django 3.0.7 on 2020-07-31 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200725_0133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='price',
        ),
        migrations.AddField(
            model_name='direccionentrega',
            name='rfc',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='direccionentrega',
            name='telefono',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
