# Generated by Django 3.0.7 on 2020-07-31 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200731_0608'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='price',
            field=models.FloatField(default=1),
        ),
    ]
